# -*- coding: utf-8 -*-
"""calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EhtV6ttXtLYPMz_1w4DG1rKjkvWrPSW3
"""

def add(n1,n2):
    return n1+n2
def subtract(n1,n2):
    return n1-n2
def multiply(n1,n2):
    return n1*n2
def divide(n1,n2):
    return n1/n2
def exponent(n1,n2):
    return n1**n2
print("Select option")
print("1.Add \t2.Subtract \t3.Multiply \t4.Divide \t5.Exponent")
while True:
    choice = input("Enter choice(1-5) : ")
    if choice in ('1', '2', '3', '4','5'):
        num1 = float(input("Enter first number : "))
        num2 = float(input("Enter second number : "))
    if choice == '1':
        print("Sum value= ", add(num1, num2))
    elif choice == '2':
        print("Difference value= ",  subtract(num1, num2))
    elif choice == '3':
        print("Product value= ", multiply(num1, num2))
    elif choice == '4':
        print("Divison value= ", divide(num1, num2))
    elif choice == '5':
        print("Exponent value=", exponent(num1, num2))
    else:
        print("Invalid Option")
    break